## Numpy

Travis Oliphant created Numpy and released it to public as Numeric in 1995 and as Numpy in 2006. 
It is written in Python and C. Now it is maintained by Python Community. 

Numpy is a powerful library that is used for numerical computing. Libraries such as Pandas and Tensorflow are build on Numpy. In Tensorflow, the output is an ndarray, which stands for n-dimensional array. 

## Arrays and Matrices 


In Numpy, matrices are two dimensional whereas arrays can be of any dimension, i.e. n-dimensional.

In [2]:
import numpy as np # here np is an alias for numpy

In [3]:
# simple way of creating an empty numpy array
# array is a numpy function, so it is always going to have (), 
# since functions have input arguments, that's why we have ()
# inside the [], we cna give values 

a = np.array([])

## NDARRAY
An ndaray is a n-dimensional array where all items are of the same type (unlike a Python data structure) and consequently use the same amount of space. There are 21 different types of objects (also called dtypes) that can be stored in ndarray, such as
* bool_ 
* byte
* short
* int_
* single
* float_
* longfloat
* complex_
* object_
* str_

For some of the dtypes, a _ to differentiate that dtype from the corresponding Python type. Such types are also called as 'enhanced scalars).  They have the same precision as the Python type.


Creating Arrays - First let's learn about different ways of create arrays in numpy. 

In [4]:
# declaring a simple one dimensional numpy array

a = [2, 6, 10] # here a is a list that contains three values
print(a, type(a), type(a[2]))

a = np.array(a) # we are converting a into a numpy array
print(a, type(a), a.dtype)

[2, 6, 10] <class 'list'> <class 'int'>
[ 2  6 10] <class 'numpy.ndarray'> int64


In [ ]:
l1 = list(range(100_000_000))

In [ ]:
%%timeit -n 23 -r 5
# -n N: the number of times you want the code to execute.
# -r N: the number of times you want the timeit() function to repeat.
sum(l1)

In [ ]:
l2 = np.array(l1)
print(l2, type(l2), l2.dtype)

In [ ]:
%%timeit -n 23 -r 5
# Several times faster!
np.sum(l2)

In [5]:
# declaring another simple one dimensional numpy array
a = np.array([1, 2, 3, 4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
# declaring a two dimensional numpy array

b = np.array([[1, 2, 3], [4, 5, 6]])
# note that we have to supply each row of the array as an item in a list
print(b, type(b))
print(b.shape) # shape will return the shape of the array, in this case we have two rows and three columns
print(b.ndim) # ndim will return the dimension of the nd array

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
(2, 3)
2


In [41]:
# declaring a numpy matrix

b = np.matrix([[1, 2, 3], [4, 5, 6]])
# note that we have to supply each row of the array as an item in a list
print(b, type(b))
print(b.shape)
print(b.ndim)

[[1 2 3]
 [4 5 6]] <class 'numpy.matrix'>
(2, 3)
2


In [11]:
# we can create a simple ndarray by using arange
# numpy.arange(n) will create an ndarray elements starting from 0 to n-1

a = np.arange(7) # will create elements starting from 0 to (7-1)
print(a)
print(type(a))

[0 1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [12]:
# we can also include negative integers
a1 = np.arange(-7, 7)
print(a1)

[-7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6]


In [43]:
# can have step size 
a2 = np.arange(start=-10, stop=10, step=2)
print(a2)

[-10  -8  -6  -4  -2   0   2   4   6   8]


In [9]:
"""
In linspace the values are computed spreading points accross the range.
"""
np.set_printoptions(precision = 3)
p = np.linspace(start = 0.0, stop = 0.20, num=10) # Try using 11?
print('The linear space: {0}'.format(p))
print(type(p))

The linear space: [0.    0.022 0.044 0.067 0.089 0.111 0.133 0.156 0.178 0.2  ]
<class 'numpy.ndarray'>


In [10]:
# Code above increases from zero 9 times.
# The code below increases 10 times.
p = np.linspace(start = 0.0, stop = 0.20, num=11) 
print('The linear space: {0}'.format(p))
print(type(p))

The linear space: [0.   0.02 0.04 0.06 0.08 0.1  0.12 0.14 0.16 0.18 0.2 ]
<class 'numpy.ndarray'>


In [11]:
"""
In logspace the values are computed by taking 10 power the value
note that 10 power 0.1 is 1.25892541
"""
p = np.logspace(start = 0.1, stop = 0.20, num=10)
print('The log space of value is {0}'.format(p))
print(type(p))

The log space of value is [1.259 1.292 1.325 1.359 1.395 1.431 1.468 1.506 1.545 1.585]
<class 'numpy.ndarray'>


In [12]:
# using zeros() method
a = np.zeros((3, 2))
print(a)

# np.zeros is used for initialization

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [13]:
# using ones()
a = np.ones((3,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
# using identity
a = np.identity(2) 
print(a)

# identity is always going to return a square nd array

[[1. 0.]
 [0. 1.]]


In [9]:
import numpy as np
# using empty() method 
# this will generate very small random numbers close to zero
np.set_printoptions(precision = 8)
b = np.empty((4,4)) 
print(b) 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Additional References:

http://people.duke.edu/~ccc14/pcfb/numpympl/NumpyBasics.html

https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

http://www.engr.ucsb.edu/~shell/che210d/numpy.pdf

http://www.labri.fr/perso/nrougier/teaching/numpy/numpy.html

http://www.labri.fr/perso/nrougier/teaching/numpy.100/

https://www.numpy.org/devdocs/user/numpy-for-matlab-users.html