In this notebook we will discuss the following:
    
- Reshape

- Resize

- ravel

- flatten

- ufunc

- broadcast

- indexing

In [4]:
import numpy as np
import inspect

def print_name_value(variable):
    frame = inspect.currentframe()
    frame = inspect.getouterframes(frame)[1]
    ctx = inspect.getframeinfo(frame[0]).code_context[0].strip()
    single_arg = ctx[ctx.find('(') + 1:-1].split(',')[0]
    mem_variable = id(variable)
    print(f'{single_arg}:\n{variable}')

In [5]:
# ndim will return number of ndarray dimensions
a = np.arange(12)
print_name_value(a) 
print(f'Num dimensions = {a.ndim}')

a:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Num dimensions = 1


In [6]:
b = np.array([[2, 5], [8, 11], [4, 17]])
print(b)
print(f'Num dimensions = {b.ndim}')

[[ 2  5]
 [ 8 11]
 [ 4 17]]
Num dimensions = 2


In [7]:
# b.shape

In [36]:
# reshape() will reshape the array into the specified shape
a = np.arange(8) # we are creating an array with value 0, 1,..., 7
b = a.reshape((2, 4)) # Change the array to size 2x4 
print_name_value(a)
print_name_value(b) 

# this works because 2*4 = 8 

a:
[0 1 2 3 4 5 6 7]
b:
[[0 1 2 3]
 [4 5 6 7]]


In [8]:
a1 = np.arange(9)
print_name_value(a1)
b1 = a1.reshape((2, 4)) # Change the array to size 2x4 
print_name_value(b1) 

# This cell failed because 2*4 is not equal to 10

a1:
[0 1 2 3 4 5 6 7 8]


ValueError: cannot reshape array of size 9 into shape (2,4)

In [9]:
# Note: Always check if operation is 'inplace' or if returns a new object.
a = np.arange(12)
print_name_value(a) 

c = a.resize((4,2))
print_name_value(c) 
# the above line will return None as resize modifies "inplace" 
# while reshape creates a new array 
print_name_value(a)

a:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
c:
None
a:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [10]:
b = np.arange(9)
print_name_value(b)
b.resize((3,3))
print_name_value(b)

b:
[0 1 2 3 4 5 6 7 8]
b:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
flat_b = b.flatten()
print_name_value(flat_b)
print_name_value(b)
# since flat_b is a new copy, any change to flat_b does not affect b

flat_b:
[0 1 2 3 4 5 6 7 8]
b:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
flat_b[0] = -100
print_name_value(flat_b)
print_name_value(b)


flat_b:
[-100    1    2    3    4    5    6    7    8]
b:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
ravel_b = b.ravel()
print(ravel_b)
# ravel_b is not a copy, any change to ravel_b affects b 

[0 1 2 3 4 5 6 7 8]


In [15]:
ravel_b[0] = 88
print_name_value(ravel_b)
print_name_value(b)
# ravel_a is not a copy, any change to ravel_a affects a 

ravel_b:
[88  1  2  3  4  5  6  7  8]
b:
[[88  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [15]:
# for a 2 dimensional array, we have to do double indexing
#   b[0][0] -> represents the first value in the first row
#   b[0][1] -> refers to the second value in the first row
#   b[0][2] -> refers to the third value in the first row
#   b[2][1] = 7 -> Assigns 7 to the element in the third row, second column.

In [10]:
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [11]:
# good time to talk about shallow copy vs deep copy

# shallow copy
d = b
b[0][0] = -4
print_name_value(b)
print_name_value(d)
# Note that d and a will have same values even though we modified only a

b:
[[-4  1  2]
 [ 3  4  5]
 [ 6  7  8]]
d:
[[-4  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [16]:
# Deep copy
e = b.copy()
e[0][0] = 300
print_name_value(b)
print_name_value(e)
# Note that e and a will have different values

b:
[[88  1  2]
 [ 3  4  5]
 [ 6  7  8]]
e:
[[300   1   2]
 [  3   4   5]
 [  6   7   8]]


## List of ufuncs short for universal functions in numpy

https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [15]:
# Universal functions are called ufunc 

a = np.linspace(0, 0.9, 10)
s = np.sin(a)
c = np.cos(a)
print_name_value(a)
print_name_value(s)
print_name_value(c)

a:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
s:
[0.         0.09983342 0.19866933 0.29552021 0.38941834 0.47942554
 0.56464247 0.64421769 0.71735609 0.78332691]
c:
[1.         0.99500417 0.98006658 0.95533649 0.92106099 0.87758256
 0.82533561 0.76484219 0.69670671 0.62160997]


In [16]:
# convert angles from radians to degrees
s1 = np.rad2deg(s)
c1 = np.rad2deg(c)
print_name_value(s1)
print_name_value(c1)

s1:
[ 0.          5.72003343 11.38291417 16.9320606  22.31202748 27.46905995
 32.35163066 36.91095457 41.10147642 44.8813259 ]
c1:
[57.29577951 57.00953927 56.15367855 54.73674884 52.77290763 50.28177697
 47.28824742 43.82222932 39.918354   35.61562769]


## Array Indexing

In [17]:
# Basic slicing
import numpy as np
o = np.random.rand(5, 5)
print_name_value(o)
a = o*6
# [
# [6,6 6,6,6],
# [6,6 6,6,6],
# [6,6 6,6,6],
# [6,6 6,6,6],
# [6,6 6,6,6]
]

print_name_value(a)
b = a.astype(int)
print_name_value(b)
print('The rows=1 and cols=2 element is {0}'.format(b[1,2])) 
print('The first col is {0}'.format(b[:,0])) # all rows for cols=0
print('The third row is {0}'.format(b[2, :])) # all cols for rows = 2

o:
[[3.76560572e-01 5.15523602e-04 2.35738357e-01 1.85391079e-01
  8.14528130e-01]
 [2.56705806e-01 5.57046393e-01 8.84154189e-01 6.82725664e-01
  7.09124941e-01]
 [2.43411898e-01 9.58260864e-01 9.62209923e-01 5.47261333e-01
  2.37044523e-01]
 [4.04832587e-01 6.62498416e-03 1.63267685e-01 2.07899463e-03
  6.57227250e-01]
 [5.63989030e-02 3.23789585e-01 4.41322746e-02 4.44942086e-01
  8.96287883e-02]]
a:
[[2.25936343e+00 3.09314161e-03 1.41443014e+00 1.11234647e+00
  4.88716878e+00]
 [1.54023484e+00 3.34227836e+00 5.30492513e+00 4.09635398e+00
  4.25474965e+00]
 [1.46047139e+00 5.74956518e+00 5.77325954e+00 3.28356800e+00
  1.42226714e+00]
 [2.42899552e+00 3.97499049e-02 9.79606110e-01 1.24739678e-02
  3.94336350e+00]
 [3.38393418e-01 1.94273751e+00 2.64793647e-01 2.66965252e+00
  5.37772730e-01]]
b:
[[2 0 1 1 4]
 [1 3 5 4 4]
 [1 5 5 3 1]
 [2 0 0 0 3]
 [0 1 0 2 0]]
The rows=1 and cols=2 element is 5
The first col is [2 1 1 2 0]
The third row is [1 5 5 3 1]


In [18]:
x1 = [2, 4, 8]
x2 = [x*2 for x in x1]
print(x2)

[4, 8, 16]


In [55]:
# No broacasting 

a = np.array([[2, 4, 8], [3, 5, 7], [4, 6, 10]])
b = np.array([[3, 2, 1], [2, 4, 4], [1, 2, 3]])
c = a + b
print_name_value(a)
print_name_value(b)
print_name_value(c)

a:
[[ 2  4  8]
 [ 3  5  7]
 [ 4  6 10]]
b:
[[3 2 1]
 [2 4 4]
 [1 2 3]]
c:
[[ 5  6  9]
 [ 5  9 11]
 [ 5  8 13]]


In [23]:
# broadcasting - the process of supplying a value to 
# every element in an array

a = np.array([[2, 4, 8], [3, 5, 7], [4, 6, 10]])
b = np.array(-1)
c = a + b
print_name_value(a)
print_name_value(b)
print_name_value(c)

a:
[[ 2  4  8]
 [ 3  5  7]
 [ 4  6 10]]
b:
-1
c:
[[1 3 7]
 [2 4 6]
 [3 5 9]]


In [25]:
# Broacasting example with Row

a = np.array([[2, 4, 8], [3, 5, 7], [4, 6, 10]])
b = np.array([1, 10, 100])
c = a + b
print_name_value(a)
print_name_value(b)
print_name_value(c)

a:
[[ 2  4  8]
 [ 3  5  7]
 [ 4  6 10]]
b:
[  1  10 100]
c:
[[  3  14 108]
 [  4  15 107]
 [  5  16 110]]


In [24]:
# Broacasting example with Column

a = np.array([[2, 4, 8], [3, 5, 7], [4, 6, 10]])
b = np.array([[1], [10], [100]])
c = a + b
print_name_value(a)
print_name_value(b)
print_name_value(c)

a:
[[ 2  4  8]
 [ 3  5  7]
 [ 4  6 10]]
b:
[[  1]
 [ 10]
 [100]]
c:
[[  3   5   9]
 [ 13  15  17]
 [104 106 110]]


In [61]:
# An example of sorting

a = np.array([[2, 5, 7], [6, 4, 3], [1, 10, 8]])
print_name_value(a)

print("Sorting along columns")
a_cp = np.sort(a, axis = 0)
print(a_cp) # along the column
a_cp[0][0] = 1000
print_name_value(a_cp)
print_name_value(a)
print("+" * 30 )
print("Sorting along rows (default)")
print(np.sort(a, axis = 1)) # along the rows, default.

a:
[[ 2  5  7]
 [ 6  4  3]
 [ 1 10  8]]
Sorting along columns
[[ 1  4  3]
 [ 2  5  7]
 [ 6 10  8]]
a_cp:
[[1000    4    3]
 [   2    5    7]
 [   6   10    8]]
a:
[[ 2  5  7]
 [ 6  4  3]
 [ 1 10  8]]
++++++++++++++++++++++++++++++
Sorting along rows (dafault)
[[ 2  5  7]
 [ 3  4  6]
 [ 1  8 10]]


In [56]:
 # we can also use sort() method to sort 
    
result = a.sort() 
# Note: np.sort(a) this will not alter a
# however, a.sort(), a is modified in place
print_name_value(result)
print("+" * 30 )
print_name_value(a) 

result:
None
++++++++++++++++++++++++++++++
a:
[[ 2  4  8]
 [ 3  5  7]
 [ 4  6 10]]
