### In this notebook we will look at

- random module

- array manipulations

In [1]:
import numpy as np
from typing import Any
import inspect

def print_name_value(variable):
    frame = inspect.currentframe()
    frame = inspect.getouterframes(frame)[1]
    ctx = inspect.getframeinfo(frame[0]).code_context[0].strip()
    single_arg = ctx[ctx.find('(') + 1:-1].split(',')[0]
    mem_variable = id(variable)
    print(f'{single_arg}:\n{variable}\n')
    
def print_titble_and_value(title: str, value: Any):
    value_str = str(value)
    print(f'{title}:\n {value_str}\n')

In [2]:
# random.rand(x) will return an ndarray with x number of items that are 
# randomly selected between 0 and 1
a = np.random.rand(3)
print_name_value(a)

a:
[0.22583745 0.63709406 0.59137728]



In [40]:
a.sort() 
print_name_value(a)

a:
[0.29346275 0.34556671 0.50340545]



In [6]:
a = np.random.rand(2, 4)
a[0][1] = 0
print_name_value(a)
print(a.dtype)
print(a.nonzero())

a:
[[0.24450398 0.         0.25787751 0.93266602]
 [0.34645734 0.3565839  0.51442777 0.83015591]]

float64
(array([0, 0, 0, 1, 1, 1, 1]), array([0, 2, 3, 0, 1, 2, 3]))


In [42]:
a = np.random.rand(2, 4)
a[1,1] = 0
print_name_value(a)
print(a.nonzero())

a:
[[0.95006674 0.07788423 0.00307339 0.77281915]
 [0.71883802 0.         0.7250848  0.63311489]]

(array([0, 0, 0, 0, 1, 1, 1]), array([0, 1, 2, 3, 0, 2, 3]))


In [43]:
# random.sample will return a random number from a uniform distribution from [0.0, 1.0)
# 1.0 is not included
c = np.random.sample()
print(c)

0.28305302507564933


In [44]:
# random.choice(n) will return a number from an ndarray n
a = np.array([2, 6, 12, 18])
print(np.random.choice(a))

2


In [9]:
"""
random.randint(x) 
  Will return an integer from the interval  [0, x], both are included

random.randint(x, y) 
  Will return an integer from [x, y]
  
random.randint(x, y, n)
  Will return n integers between x and y
"""

print_titble_and_value('A value between 0 and 4', np.random.randint(5)) 
print_titble_and_value('A value between 11 and 14', np.random.randint(11, 15)) 
print_titble_and_value('Two values between -10 and -5', np.random.randint(-10, -5, 2)) 
print_titble_and_value('A 2 x 3 matrix', np.random.randint(1, 5, [2, 3])) 
# Note that both values can be the same.


A value between 0 and 4:
 1

A value between 11 and 14:
 11

Two values between -10 and -5:
 [-9 -9]

A 2 x 3 matrix:
 [[1 4 2]
 [3 4 4]]



In [10]:
list1 = ["Elizabeth", "Lisa", "Asha", "Mike", "Amit"]
import random
c = random.choice(list1)
print(c)

Mike


In [11]:
lista = ["Elizabeth", "Lisa", "Asha", "Mike", "Amit"]
print("lista is: ", lista)
print("Pick a random name from list: ", lista[np.random.randint(len(lista))])
print(np.random.choice(lista))

lista is:  ['Elizabeth', 'Lisa', 'Asha', 'Mike', 'Amit']
Pick a random name from list:  Asha
Amit


In [48]:
# Using random.rand create a 1D ndarray, then convert the values in the ndarray to integer 
# and then choose a value from the new int ndarray. At every step print the output. 

n2 = np.array([2.1, 4.2, 7.4, 9.8])
print_name_value(n2)
n3 = n2.astype(int)
print_name_value(n3)

nchoose = np.random.choice(n3)
print_name_value(nchoose)

n2:
[2.1 4.2 7.4 9.8]

n3:
[2 4 7 9]

nchoose:
9



In [51]:
ne = np.random.rand(2,4)
print_name_value(ne)
print('Dimension of ne = {0}'.format(ne.ndim))

ne:
[[0.8205487  0.66196085 0.08808666 0.0915836 ]
 [0.58954446 0.38249883 0.29074952 0.54207693]]

Dimension of ne = 2


#### Now we will look at the array manipulation

In [13]:
a = np.array([[2, 4], [7, 9]])
b = np.array([[1, 3], [6, 5]])
print_name_value(a)
print_name_value(b)


a:
[[2 4]
 [7 9]]

b:
[[1 3]
 [6 5]]



In [14]:
# using + operator we can compute element by element sum of two arrays
print_name_value(a + b)


a + b:
[[ 3  7]
 [13 14]]



In [15]:
# using * operator we can compute element by element multiplication of two arrays
print(a * b) # element by element multiplication


[[ 2 12]
 [42 45]]


In [16]:
# using - operator we can compute element by element subtraction of two arrays
print_name_value(a - b)


a - b:
[[1 1]
 [1 4]]



In [17]:
# dot(a1, a2) will compute matrix multiplication
print(np.dot(a, b)) # matrix multiplication


[[26 26]
 [61 66]]


In [18]:
# The @ operator can be used to perform matrix multiplication 
# @  is called the 'infix' operator and is only available in Python 3.5+ (PEP 465)
print(a @ b)


[[26 26]
 [61 66]]


In [19]:
# We can also perfrom matrix multiplication using matmul(a1, a2)
print(np.matmul(a, b)) # matrix multiplication


[[26 26]
 [61 66]]


In [58]:
# in an array transpose() will interchange the rows to columns 
# and vice-versa 
x = np.matrix([[4, 7, 9], [5, 7, 10]])
print(x)
print(' ')
print(np.transpose(x))


[[ 4  7  9]
 [ 5  7 10]]
 
[[ 4  5]
 [ 7  7]
 [ 9 10]]


In [59]:
# T can also be used to transpose a matrix

y = np.array([[3, 5, 1], [8, 11, 0]])
print("Original array:")
print(y)
print("Transposed array:")
print(y.T)

Original array:
[[ 3  5  1]
 [ 8 11  0]]
Transposed array:
[[ 3  8]
 [ 5 11]
 [ 1  0]]
