In this notebook we will discuss the following:
    
- Reshape

- Resize

- ravel

- flatten

- ufunc

- broadcast

- indexing

In [32]:
import numpy as np
import inspect

def print_name_value(variable):
    frame = inspect.currentframe()
    frame = inspect.getouterframes(frame)[1]
    ctx = inspect.getframeinfo(frame[0]).code_context[0].strip()
    single_arg = ctx[ctx.find('(') + 1:-1].split(',')[0]
    mem_variable = id(variable)
    print(f'{single_arg}:\n{variable}')

In [34]:
# ndim will return number of ndarray dimensions
a = np.arange(12)
print_name_value(a) 
print(f'Num dimensions = {a.ndim}')

a:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Num dimensions = 1


In [35]:
b = np.array([[2, 5], [8, 11], [4, 17]])
print(b)
print(f'Num dimensions = {b.ndim}')

[[ 2  5]
 [ 8 11]
 [ 4 17]]
Num dimensions = 2


In [36]:
# reshape() will reshape the array into the specified shape
a = np.arange(8) # we are creating an array with value 0, 1,..., 7
b = a.reshape((2, 4)) # Change the array to size 2x4 
print_name_value(a)
print_name_value(b) 

# this works because 2*4 = 8 

a:
[0 1 2 3 4 5 6 7]
b:
[[0 1 2 3]
 [4 5 6 7]]


In [39]:
a1 = np.arange(10)
b1 = a1.reshape((2, 4)) # Change the array to size 2x4 
print_name_value(a1)
print_name_value(b1) 

# This cell failed because 2*4 is not equal to 10

ValueError: cannot reshape array of size 10 into shape (2,4)

In [41]:
# Note: Always check if operation is 'inplace' or if returns a new object.
a = np.arange(12)
print_name_value(a) 

c = a.resize((4,2))
print_name_value(c) 
# the above line will return None as resize modifies "inplace" 
# while reshape creates a new array 
print_name_value(a)

a:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
c:
None
a:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [46]:
b = np.arange(9)
print_name_value(b)
b.resize((3,3))
print_name_value(b)

b:
[0 1 2 3 4 5 6 7 8]
b:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [47]:
flat_b = b.flatten()
print_name_value(flat_b)
print_name_value(b)
# since flat_b is a new copy, any change to flat_b does not affect b

flat_b:
[0 1 2 3 4 5 6 7 8]
b:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [48]:
flat_b[0] = -100
print_name_value(flat_b)
print_name_value(b)


flat_b:
[-100    1    2    3    4    5    6    7    8]
b:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [50]:
ravel_b = b.ravel()
print(ravel_b)
# ravel_b is not a copy, any change to ravel_b affects b 

[0 1 2 3 4 5 6 7 8]


In [52]:
ravel_b[0] = 100
print_name_value(ravel_b)
print_name_value(b)
# ravel_a is not a copy, any change to ravel_a affects a 

ravel_b:
[100   1   2   3   4   5   6   7   8]
b:
[[100   1   2]
 [  3   4   5]
 [  6   7   8]]


In [15]:
# for a 2 dimensional array, we have to do double indexing
#   b[0][0] -> represents the first value in the first row
#   b[0][1] -> rrefers to the second value in the first row
#   b[0][2] -> rrefers to the third value in the first row
#   b[2][1] = 7 -> Assigns 7 to the element in the third row, second column.

In [10]:
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [11]:
# good time to talk about shallow copy vs deep copy

# shallow copy
d = b
b[0][0] = -4
print_name_value(b)
print_name_value(d)
# Note that d and a will have same values even though we modified only a

b:
[[-4  1  2]
 [ 3  4  5]
 [ 6  7  8]]
d:
[[-4  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [12]:
# Deep copy
e = b.copy()
e[0][0] = 300
print_name_value(b)
print_name_value(e)
# Note that e and a will have different values

b:
[[-4  1  2]
 [ 3  4  5]
 [ 6  7  8]]
e:
[[300   1   2]
 [  3   4   5]
 [  6   7   8]]


## List of ufuncs short for universal functions in numpy

https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [15]:
# Universal functions are called ufunc 

a = np.linspace(0, 0.9, 10)
s = np.sin(a)
c = np.cos(a)
print_name_value(a)
print_name_value(s)
print_name_value(c)

a:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
s:
[0.         0.09983342 0.19866933 0.29552021 0.38941834 0.47942554
 0.56464247 0.64421769 0.71735609 0.78332691]
c:
[1.         0.99500417 0.98006658 0.95533649 0.92106099 0.87758256
 0.82533561 0.76484219 0.69670671 0.62160997]


In [16]:
# convert angles from radians to degrees
s1 = np.rad2deg(s)
c1 = np.rad2deg(c)
print_name_value(s1)
print_name_value(c1)

s1:
[ 0.          5.72003343 11.38291417 16.9320606  22.31202748 27.46905995
 32.35163066 36.91095457 41.10147642 44.8813259 ]
c1:
[57.29577951 57.00953927 56.15367855 54.73674884 52.77290763 50.28177697
 47.28824742 43.82222932 39.918354   35.61562769]


## Array Indexing

In [54]:
# Basic slicing
import numpy as np
o = np.random.rand(5, 5)
print_name_value(o)
a = o*5
print_name_value(a)
b = a.astype(int)
print_name_value(b)
print('The rows=1 and cols=2 element is {0}'.format(b[1,2])) 
print('The first col is {0}'.format(b[:,0])) # all rows for cols=0
print('The third row is {0}'.format(b[2, :])) # all cols for rows = 2

o:
[[0.2062194  0.45131925 0.11784747 0.31509937 0.65317872]
 [0.54887855 0.40638179 0.30109821 0.22814778 0.73780777]
 [0.10693329 0.27234319 0.37294863 0.66802181 0.97626987]
 [0.56407372 0.54020102 0.26890906 0.43177704 0.22845432]
 [0.90362598 0.09657301 0.8379094  0.61997304 0.26809246]]
a:
[[1.03109699 2.25659626 0.58923736 1.57549685 3.26589359]
 [2.74439277 2.03190895 1.50549104 1.1407389  3.68903887]
 [0.53466644 1.36171595 1.86474313 3.34010907 4.88134934]
 [2.82036862 2.70100509 1.34454528 2.15888522 1.14227161]
 [4.51812991 0.48286506 4.18954701 3.09986521 1.34046228]]
b:
[[1 2 0 1 3]
 [2 2 1 1 3]
 [0 1 1 3 4]
 [2 2 1 2 1]
 [4 0 4 3 1]]
The rows=1 and cols=2 element is 1
The first col is [1 2 0 2 4]
The third row is [0 1 1 3 4]


In [18]:
x1 = [2, 4, 8]
x2 = [x*2 for x in x1]
print(x2)

[4, 8, 16]


In [55]:
# No broacasting 

a = np.array([[2, 4, 8], [3, 5, 7], [4, 6, 10]])
b = np.array([[3, 2, 1], [2, 4, 4], [1, 2, 3]])
c = a + b
print_name_value(a)
print_name_value(b)
print_name_value(c)

a:
[[ 2  4  8]
 [ 3  5  7]
 [ 4  6 10]]
b:
[[3 2 1]
 [2 4 4]
 [1 2 3]]
c:
[[ 5  6  9]
 [ 5  9 11]
 [ 5  8 13]]


In [23]:
# broadcasting - the process of supplying a value to 
# every element in an array

a = np.array([[2, 4, 8], [3, 5, 7], [4, 6, 10]])
b = np.array(-1)
c = a + b
print_name_value(a)
print_name_value(b)
print_name_value(c)

a:
[[ 2  4  8]
 [ 3  5  7]
 [ 4  6 10]]
b:
-1
c:
[[1 3 7]
 [2 4 6]
 [3 5 9]]


In [25]:
# Broacasting example with Row

a = np.array([[2, 4, 8], [3, 5, 7], [4, 6, 10]])
b = np.array([1, 10, 100])
c = a + b
print_name_value(a)
print_name_value(b)
print_name_value(c)

a:
[[ 2  4  8]
 [ 3  5  7]
 [ 4  6 10]]
b:
[  1  10 100]
c:
[[  3  14 108]
 [  4  15 107]
 [  5  16 110]]


In [24]:
# Broacasting example with Column

a = np.array([[2, 4, 8], [3, 5, 7], [4, 6, 10]])
b = np.array([[1], [10], [100]])
c = a + b
print_name_value(a)
print_name_value(b)
print_name_value(c)

a:
[[ 2  4  8]
 [ 3  5  7]
 [ 4  6 10]]
b:
[[  1]
 [ 10]
 [100]]
c:
[[  3   5   9]
 [ 13  15  17]
 [104 106 110]]


In [61]:
# An example of sorting

a = np.array([[2, 5, 7], [6, 4, 3], [1, 10, 8]])
print_name_value(a)

print("Sorting along columns")
a_cp = np.sort(a, axis = 0)
print(a_cp) # along the column
a_cp[0][0] = 1000
print_name_value(a_cp)
print_name_value(a)
print("+" * 30 )
print("Sorting along rows (dafault)")
print(np.sort(a, axis = 1)) # along the rows, default.

a:
[[ 2  5  7]
 [ 6  4  3]
 [ 1 10  8]]
Sorting along columns
[[ 1  4  3]
 [ 2  5  7]
 [ 6 10  8]]
a_cp:
[[1000    4    3]
 [   2    5    7]
 [   6   10    8]]
a:
[[ 2  5  7]
 [ 6  4  3]
 [ 1 10  8]]
++++++++++++++++++++++++++++++
Sorting along rows (dafault)
[[ 2  5  7]
 [ 3  4  6]
 [ 1  8 10]]


In [56]:
 # we can also use sort() method to sort 
    
result = a.sort() 
# Note: np.sort(a) this will not alter a
# however, a.sort(), a is modified in place
print_name_value(result)
print("+" * 30 )
print_name_value(a) 

result:
None
++++++++++++++++++++++++++++++
a:
[[ 2  4  8]
 [ 3  5  7]
 [ 4  6 10]]
