### In this notebook we will discuss Boolean Operations

Boolean returns True or False values

In [20]:
import numpy as np
import inspect

def print_name_value(variable):
    frame = inspect.currentframe()
    frame = inspect.getouterframes(frame)[1]
    ctx = inspect.getframeinfo(frame[0]).code_context[0].strip()
    single_arg = ctx[ctx.find('(') + 1:-1].split(',')[0]
    mem_variable = id(variable)
    print(f'{single_arg}:\n{variable}')

In [21]:
c = np.array([[4, 2, 6],[7, 10, 11]], dtype=np.float32)
d = np.linspace(start=10, stop=13, num=3)
print_name_value(c)
print_name_value(d)

c:
[[ 4.  2.  6.]
 [ 7. 10. 11.]]
d:
[10.  11.5 13. ]


In [22]:
f = 10*c 
# Ssimilar to broadcasting,
# we are multiplying every element in c by 10.

# Multiply a matrix with scalar. 
# The matrix e is of dtype=int64 but the final matrix is of dtype=float64
print(f, f.dtype)


[[ 40.  20.  60.]
 [ 70. 100. 110.]] float32


In [23]:
f = d-c # Subtract matrix
print(f, f.dtype)


[[6.  9.5 7. ]
 [3.  1.5 2. ]] float64


In [24]:
h = f > 5 # Compare every element with the value of 5
print_name_value(h)

h:
[[ True  True  True]
 [False False False]]


In [6]:
# Indexing with boolean arrays
k = f > 5
print_name_value(f)
print_name_value(k)
print(' ')
print('Prints the values that idexes are true')
print(f[k]) # Returns values in f that are True in k


f:
[[6.  9.5 7. ]
 [3.  1.5 2. ]]
k:
[[ True  True  True]
 [False False False]]
 
Prints the values that idexes are true
[6.  9.5 7. ]


In [25]:
print(f[f>5]) 
# This is same as the previous line except that we are 
# not creating a new array k

[6.  9.5 7. ]


In [26]:
t = np.array([[-2, 4, -3],[-1, 7, 0]])

In [27]:
t1 = t > -3
print_name_value(t1)

t1:
[[ True  True False]
 [ True  True  True]]


In [28]:
print(t[t1])

[-2  4 -1  7  0]


In [29]:
print(t[t > -3])

[-2  4 -1  7  0]


In [30]:
# where(condition) will returns indices where the condition is true 

a = np.array([[7, 8, 4],[5, 6, 9]]) 
print_name_value(a)
print(' ')
print(a > 5)
print("indices where the value is greater than 5: ")

b = np.where(a>5)
print_name_value(b)


a:
[[7 8 4]
 [5 6 9]]
 
[[ True  True False]
 [False  True  True]]
indices where the value is greater than 5: 
b:
(array([0, 0, 1, 1]), array([0, 1, 1, 2]))


In [13]:
# any(z) returns a boolean value when a certain 
# condition is met in z at least once
print(np.any(a > 6)) 


True


In [31]:
# All (z) returns a boolean value when a certain condition is met by ALL the elements in z
print(np.all(a>7)) # since not all values are greater than 7


False


In [32]:
# logical_and will values from the AND logical operation.
print(np.logical_and(True, False))


False


In [33]:
print(np.logical_and(True, True))


True


In [34]:
print(np.logical_and(False, False))


False


In [35]:
print(np.logical_and([False, False, True], [False, True, True]))


[False False  True]


In [36]:
# logical_and with two conditions
s1 = np.array([3, 6, 9, 12])
print(np.logical_and(s1>5, s1%2==0))


[False  True False  True]
